# Generated by Django 5.0.6 on 2024-05-18 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Job Ocupation')),
                ('company', models.CharField(max_length=100, verbose_name='Company name')),
                ('start_date', models.DateField(verbose_name='Start date of work')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date of work')),
                ('localization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.localization')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.IntegerField(default=1, help_text='Enter value in range(0,10) ', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Advanced Level')),
                ('projects', models.ManyToManyField(blank=True, related_name='related_projects', to='main.project')),
            ],
        ),
    ]
